### ISSUE TITLE
Parse function returns posted_date  as nil for the field <DTPOSTED> with [gmt offset[:tz name]]

### ISSUE THREAD

**Issue by nikhilmore54-zz** [jjcarstens/ofex#13]
Hello,
I am passing various OFX and QFX files. The file is parsed at large but for one field called posted_date returns a nil value.
Also somehow, Ofex.parse! is not being called 
I am on Ofex 0.2.0

**Comment by jjcarstens** [comment]
Thanks @nikhilmore54.

Do you have some reproducible steps or examples? It could be that `posted_date` is missing, or there is some identifier we just need to account for and would be best to see some of your examples that are failing.

As for `Ofex.parse!`, I'm not sure what you mean there either. That is an explicit function that you must call if you're wanting to use it, so maybe an issue with your setup as well?

**Comment by nikhilmore54-zz** [comment]
Hello dev,

I will take do so when i gey back home.

**Comment by nikhilmore54-zz** [comment]
Added the files giving error as a zip file
the data 
```<
STMTTRN>
	<TRNTYPE>DEBIT
	<DTPOSTED>20180807120000
	<TRNAMT>-148.33
	<FITID>191063861201808060000002
	<NAME>PROG DIRECT INS  INS PREM
	<MEMO>Preauthorized Debit
</STMTTRN>
```
is parsed correctly, however the following is parsed as having a nil date_posted value
```
<STMTTRN>
	<TRNTYPE>POS
	<DTPOSTED>20180810120000[-5:EST]
	<TRNAMT>-72.40
	<FITID>20180815000000[-5:EST]*-72.40*13**POS Withdrawal TOYO STEAK
	<NAME>POS Withdrawal TOYO STEAK
	<MEMO>HOUSE INWOONSOCKET RIUS
</STMTTRN>
```



[files_date_nil.zip](https://github.com/jjcarstens/ofex/files/2362982/files_date_nil.zip)

**Comment by jjcarstens** [comment]
@nikhilmore54 What version of Ofex are you using? I just ran all of your files through the latest version (`0.2.3`) and every transaction came out with a `posted_date` value. Even running your example above returns an expected date value as well so I'm not quite able to reproduce.

**Comment by nikhilmore54-zz** [comment]
Its 0.2.0

**Comment by jjcarstens** [comment]
That’s the problem then. That behavior was addresses in v0.2.1. 

Update to the latest (or 0.2.1 minimum) and you should be good.
