### ISSUE TITLE
The parser creates a single account map for multiple accounts 

### ISSUE THREAD

**Issue by nikhilmore54-zz** [jjcarstens/ofex#14]
Hello Developer, 
I have found a bug where multiple accounts are stored in a single map. A sample file is attached along with its output. Kindly notice how the account number of multiple accounts is concatenated into a long string. 
[usaa_quicken_1.zip](https://github.com/jjcarstens/ofex/files/2450862/usaa_quicken_1.zip)

the solution from my side is attached as a code  by replacing the code for `parse_message_set` in ofex.ex with 
`defp parse_message_set("BANKMSGSRSV1", message_set) do
    message_set
    |> xpath(~x"//BANKMSGSRSV1/*[contains(name(), 'STMTTRNRS')]"l)
    |> Enum.map(&BankAccount.create(&1))
  end
  defp parse_message_set("CREDITCARDMSGSRSV1", message_set) do
    message_set
    |> xpath(~x"//BANKMSGSRSV1/*[contains(name(), 'STMTTRNRS')]"l)
    |> Enum.map(&CreditCardAccount.create(&1))
  end`

**Comment by jjcarstens** [comment]
resolved with #15
